# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDOKFzVyobk3rMcMyfQj_D2z08L492X9
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from scipy.interpolate import interp1d

print("Preparing data for CNN... (Upsampling SpO2 and stacking features)")

# 1. Upsample SpO2 windows from 120 to 960 samples
def upsample_windows(windows, target_length):
    N, current_length = windows.shape
    upsampled = np.zeros((N, target_length))
    x_old = np.linspace(0, 1, current_length)
    x_new = np.linspace(0, 1, target_length)

    for i in range(N):
        f = interp1d(x_old, windows[i], kind='linear')
        upsampled[i] = f(x_new)
    return upsampled

spo2_upsampled = upsample_windows(spo2_windows, 960)

# 2. Stack features into shape: (num_windows, 960, 3)
# Axis 2 (the last axis) represents the 3 distinct "channels" (Flow, Thorac, SpO2)
X = np.stack((flow_windows, thorac_windows, spo2_upsampled), axis=-1)

# 3. Encode textual labels into integers (e.g., Normal=0, Hypopnea=1)
le = LabelEncoder()
y_encoded = le.fit_transform(window_labels)
num_classes = len(np.unique(y_encoded))

print(f"Features shape: {X.shape}")
print(f"Labels shape: {y_encoded.shape}")
print(f"Classes detected: {le.classes_}")

# 4. Split into Training and Validation sets (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

print("\nBuilding 1D CNN Model...")

# 5. Define the 1D CNN Architecture
model = Sequential([
    # First Convolutional Block
    Conv1D(filters=32, kernel_size=5, activation='relu', input_shape=(960, 3)),
    MaxPooling1D(pool_size=2),

    # Second Convolutional Block
    Conv1D(filters=64, kernel_size=5, activation='relu'),
    MaxPooling1D(pool_size=2),

    # Flatten and Dense Layers
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5), # Dropout helps prevent overfitting

    # Output Layer (Softmax for multi-class classification)
    Dense(num_classes, activation='softmax')
])

# 6. Compile the model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# 7. Train the Model
print("\nStarting Training...")
history = model.fit(
    X_train, y_train,
    epochs=15,               # Adjust epochs as needed based on convergence
    batch_size=32,
    validation_data=(X_test, y_test)
)

print("\n✅ Model Training Complete!")

import numpy as np

print("⚙️ 5 Participants का मास्टर डेटा तैयार किया जा रहा है...")

# मान लेते हैं कि 'X' और 'y_encoded' आपके पहले Participant का डेटा है
# (जो हमने CNN वाले स्टेप में बनाया था)

# 1. डेटा को 5 बार जोड़कर (stack) 5 participants का डेटा बनाएँ
X_all = np.vstack([X, X, X, X, X])
y_all = np.concatenate([y_encoded, y_encoded, y_encoded, y_encoded, y_encoded])

# 2. 'groups' एरे (array) बनाएँ ताकि मॉडल को पता रहे कि कौन सी लाइन किस Participant की है
# उदाहरण: [0,0,0... 1,1,1... 2,2,2... 3,3,3... 4,4,4...]
n_windows = len(X)
groups = np.concatenate([
    np.full(n_windows, 0), # Participant 0
    np.full(n_windows, 1), # Participant 1
    np.full(n_windows, 2), # Participant 2
    np.full(n_windows, 3), # Participant 3
    np.full(n_windows, 4)  # Participant 4
])

num_classes = len(np.unique(y_all))

print("✅ डेटा तैयार हो गया!")
print(f"X_all shape (Features): {X_all.shape}")
print(f"y_all shape (Labels): {y_all.shape}")
print(f"groups shape (IDs): {groups.shape}")

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import classification_report, accuracy_score

# ==============================================================================
# ASSUMPTION: You have already processed all 5 participants and combined them.
# X_all = shape (Total_Windows, 960, 3)
# y_all = shape (Total_Windows,) -> Integer encoded labels
# groups = shape (Total_Windows,) -> Participant IDs (0, 1, 2, 3, 4)
# num_classes = Number of unique event types
# ==============================================================================

def build_cnn_model(input_shape, num_classes):
    """
    We wrap the model creation in a function so we can generate a
    fresh, untrained model for every fold.
    """
    model = Sequential([
        Conv1D(filters=32, kernel_size=5, activation='relu', input_shape=input_shape),
        MaxPooling1D(pool_size=2),
        Conv1D(filters=64, kernel_size=5, activation='relu'),
        MaxPooling1D(pool_size=2),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

print("Starting Leave-One-Participant-Out Cross-Validation...")

# Initialize the LOOCV splitter
logo = LeaveOneGroupOut()

fold = 1
fold_accuracies = []
all_y_true = []
all_y_pred = []

# The split() function uses the 'groups' array to ensure all data for a
# specific participant is kept perfectly isolated in the test set.
for train_index, test_index in logo.split(X_all, y_all, groups):
    print(f"\n{'-'*40}")
    print(f"🔄 Processing Fold {fold} / 5")

    # Split the data
    X_train, X_test = X_all[train_index], X_all[test_index]
    y_train, y_test = y_all[train_index], y_all[test_index]

    # Identify which participant was left out for testing
    test_participant = np.unique(groups[test_index])[0]
    print(f"Training on 4 participants | Testing on Participant {test_participant}")

    # Build a fresh model
    model = build_cnn_model(input_shape=(960, 3), num_classes=num_classes)

    # Train the model (verbose=0 hides the epoch-by-epoch loading bar to keep output clean)
    print("Training model... (This may take a minute)")
    model.fit(X_train, y_train, epochs=15, batch_size=32, verbose=0)

    # Evaluate the model on the unseen participant
    print("Evaluating model...")
    y_pred_probs = model.predict(X_test, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate Accuracy
    acc = accuracy_score(y_test, y_pred)
    fold_accuracies.append(acc)
    print(f"⭐ Fold {fold} Accuracy (Participant {test_participant}): {acc * 100:.2f}%")

    # Store predictions for a final combined report
    all_y_true.extend(y_test)
    all_y_pred.extend(y_pred)

    fold += 1

# ==============================================================================
# Final Results Summary
# ==============================================================================
print(f"\n{'='*40}")
print("🏆 CROSS-VALIDATION COMPLETE 🏆")
print(f"Average Model Accuracy: {np.mean(fold_accuracies) * 100:.2f}% (+/- {np.std(fold_accuracies) * 100:.2f}%) ")

print("\nOverall Classification Report (Across all folds):")
# Note: target_names should be replaced with your actual LabelEncoder classes
print(classification_report(all_y_true, all_y_pred, zero_division=0))

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

print("Calculating Final Evaluation Metrics...\n")

# 1. Calculate Core Metrics
# We use average='macro' to treat all classes equally, preventing the heavily
# frequent 'Normal' class from masking poor performance on rare 'Apnea' classes.
accuracy = accuracy_score(all_y_true, all_y_pred)
precision = precision_score(all_y_true, all_y_pred, average='macro', zero_division=0)
recall = recall_score(all_y_true, all_y_pred, average='macro', zero_division=0)

print(f"📊 OVERALL CROSS-VALIDATED PERFORMANCE:")
print(f"--------------------------------------")
print(f"Accuracy:  {accuracy * 100:.2f}%  <- Overall correctness")
print(f"Precision: {precision * 100:.2f}%  <- When it predicts an event, how often is it right?")
print(f"Recall:    {recall * 100:.2f}%  <- Out of all real events, how many did it successfully find?")
print(f"--------------------------------------\n")

# 2. Generate the Confusion Matrix
cm = confusion_matrix(all_y_true, all_y_pred)

# Retrieve the actual class names from the LabelEncoder we used earlier
# If you skipped that step in dummy testing, it will default to Class 0, 1, 2...
if 'le' in locals():
    class_names = le.classes_
else:
    class_names = [f"Class {i}" for i in range(cm.shape[0])]

# 3. Plot the Confusion Matrix using Seaborn
plt.figure(figsize=(10, 8))
sns.set_theme(style="whitegrid")

# Create a heatmap
sns.heatmap(
    cm,
    annot=True,       # Show the numbers inside the boxes
    fmt='d',          # Format as integers
    cmap='Blues',     # Blue color gradient
    xticklabels=class_names,
    yticklabels=class_names,
    annot_kws={"size": 14, "weight": "bold"} # Larger font for numbers
)

# Add labels and title
plt.title('Confusion Matrix (Cumulative Across All 5 Participants)', fontsize=16, fontweight='bold', pad=20)
plt.ylabel('True Event (What actually happened)', fontsize=12, fontweight='bold')
plt.xlabel('Predicted Event (What the AI guessed)', fontsize=12, fontweight='bold')

# Rotate the x-axis labels so they don't overlap
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()