# -*- coding: utf-8 -*-
"""vis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sGNz7Y9lj17LmoEIDLt_PNATtnGrWW-S
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

def load_and_parse_sleep_data(filepath):
    """
    Loads sleep signal data, skipping metadata headers,
    and parses the custom timestamp format.
    """
    # The data points start on line 8 (index 7) after the "Data:" header
    df = pd.read_csv(filepath, sep=';', skiprows=7, header=None, names=['timestamp', 'value'])

    # Clean up any trailing whitespace in timestamps
    df['timestamp'] = df['timestamp'].str.strip()

    # Parse the custom European datetime format with milliseconds (e.g., '30.05.2024 20:59:00,000')
    df['timestamp'] = pd.to_datetime(df['timestamp'], format='%d.%m.%Y %H:%M:%S,%f')

    # Downsample the data (optional but recommended for 8-hour plots to save memory)
    # df = df.iloc[::10, :] # Uncomment this to plot every 10th point if rendering is too slow

    return df

print("Loading data files... (This may take a moment due to high sample rates)")

# Load the participant's data
flow_df = load_and_parse_sleep_data('Flow - 30-05-2024.txt')
thorac_df = load_and_parse_sleep_data('Thorac - 30-05-2024.txt')
spo2_df = load_and_parse_sleep_data('SPO2 - 30-05-2024.txt')

print("Generating plots...")

# Create a 3-panel stacked plot sharing the same X-axis (Time)
fig, axs = plt.subplots(3, 1, figsize=(15, 10), sharex=True)
fig.suptitle('8-Hour Sleep Session Overview (30-05-2024)', fontsize=16)

# 1. Plot Nasal Airflow
axs[0].plot(flow_df['timestamp'], flow_df['value'], color='#1f77b4', linewidth=0.5)
axs[0].set_title('Nasal Airflow (32 Hz)', loc='left', fontsize=12)
axs[0].set_ylabel('Airflow Amplitude')
axs[0].grid(True, alpha=0.3)

# 2. Plot Thoracic Movement
axs[1].plot(thorac_df['timestamp'], thorac_df['value'], color='#2ca02c', linewidth=0.5)
axs[1].set_title('Thoracic Movement (32 Hz)', loc='left', fontsize=12)
axs[1].set_ylabel('Movement Amplitude')
axs[1].grid(True, alpha=0.3)

# 3. Plot SpO2
axs[2].plot(spo2_df['timestamp'], spo2_df['value'], color='#d62728', linewidth=1)
axs[2].set_title('SpO₂ Blood Oxygen Saturation (4 Hz)', loc='left', fontsize=12)
axs[2].set_ylabel('SpO₂ (%)')
axs[2].set_xlabel('Time (HH:MM)')
# Typical SpO2 ranges stay above 80%, setting limits helps spot desaturations easily
axs[2].set_ylim(75, 100)
axs[2].grid(True, alpha=0.3)

# Format the X-axis to cleanly show hours and minutes
axs[2].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
plt.xticks(rotation=45)

# Adjust layout to prevent overlapping labels and display
plt.tight_layout()
plt.subplots_adjust(top=0.93)
plt.show()

# Step 1: Import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import os

print("डेटा लोड किया जा रहा है... (कृपया 1-2 मिनट प्रतीक्षा करें)")

# Check if files exist in the current directory
required_files = [
    'Flow - 30-05-2024.txt',
    'Thorac - 30-05-2024.txt',
    'SPO2 - 30-05-2024.txt',
    'Flow Events - 30-05-2024.txt'
]

missing_files = [f for f in required_files if not os.path.exists(f)]

if missing_files:
    print(f"⚠️ Error: ये फाइल्स नहीं मिलीं: {missing_files}")
    print("कृपया चेक करें कि आपने फाइल्स सही नाम से Colab के फाइल सेक्शन में अपलोड की हैं या नहीं।")
else:
    # Step 2: Continuous signal data (Flow, Thorac, SPO2) को प्रोसेस करने का फंक्शन
    def load_and_parse_sleep_data(filepath):
        df = pd.read_csv(filepath, sep=';', skiprows=7, header=None, names=['timestamp', 'value'])
        df['timestamp'] = df['timestamp'].str.strip()
        df['timestamp'] = pd.to_datetime(df['timestamp'], format='%d.%m.%Y %H:%M:%S,%f')

        # NOTE: अगर Colab का RAM फुल हो जाता है, तो नीचे वाली लाइन से '#' हटा दें (इससे डेटा हल्का हो जाएगा)
        # df = df.iloc[::5, :]
        return df

    # Step 3: स्लीप इवेंट्स (Apnea/Hypopnea) को प्रोसेस करने का फंक्शन
    def load_events_data(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()[5:]

        events = []
        for line in lines:
            if not line.strip(): continue
            parts = line.split(';')
            if len(parts) >= 3:
                time_part = parts[0].strip()
                event_type = parts[2].strip()

                date_start, end_time = time_part.split('-')
                start_dt_str = date_start.strip()

                date_str = start_dt_str.split(' ')[0]
                end_dt_str = f"{date_str} {end_time.strip()}"

                start_dt = pd.to_datetime(start_dt_str, format='%d.%m.%Y %H:%M:%S,%f')
                end_dt = pd.to_datetime(end_dt_str, format='%d.%m.%Y %H:%M:%S,%f')

                if end_dt < start_dt:
                    end_dt += pd.Timedelta(days=1)

                events.append({'start': start_dt, 'end': end_dt, 'type': event_type})
        return pd.DataFrame(events)

    # Step 4: डेटा फाइल्स को लोड करें
    flow_df = load_and_parse_sleep_data('Flow - 30-05-2024.txt')
    thorac_df = load_and_parse_sleep_data('Thorac - 30-05-2024.txt')
    spo2_df = load_and_parse_sleep_data('SPO2 - 30-05-2024.txt')
    events_df = load_events_data('Flow Events - 30-05-2024.txt')

    print("📊 ग्राफ तैयार किया जा रहा है...")

    # Step 5: ग्राफ बनाना (Plotting)
    fig, axs = plt.subplots(3, 1, figsize=(15, 10), sharex=True)
    fig.suptitle('8-Hour Sleep Session with Event Annotations (30-05-2024)', fontsize=16, fontweight='bold')

    # 1. Nasal Airflow
    axs[0].plot(flow_df['timestamp'], flow_df['value'], color='#1f77b4', linewidth=0.5)
    axs[0].set_title('Nasal Airflow (32 Hz)', loc='left', fontsize=12, fontweight='bold')
    axs[0].set_ylabel('Amplitude')
    axs[0].grid(True, alpha=0.3)

    # 2. Thoracic Movement
    axs[1].plot(thorac_df['timestamp'], thorac_df['value'], color='#2ca02c', linewidth=0.5)
    axs[1].set_title('Thoracic Movement (32 Hz)', loc='left', fontsize=12, fontweight='bold')
    axs[1].set_ylabel('Amplitude')
    axs[1].grid(True, alpha=0.3)

    # 3. SpO2
    axs[2].plot(spo2_df['timestamp'], spo2_df['value'], color='#17becf', linewidth=1.5)
    axs[2].set_title('SpO₂ Blood Oxygen Saturation (4 Hz)', loc='left', fontsize=12, fontweight='bold')
    axs[2].set_ylabel('SpO₂ (%)')
    axs[2].set_xlabel('Time (HH:MM)')
    axs[2].set_ylim(70, 100)
    axs[2].grid(True, alpha=0.3)

    # --- Events Overlay (कलर शेडिंग) ---
    event_colors = {
        'Obstructive Apnea': 'red',
        'Hypopnea': 'orange',
        'Central Apnea': 'purple',
        'Mixed Apnea': 'brown'
    }

    for ax in axs:
        for _, row in events_df.iterrows():
            event_color = event_colors.get(row['type'], 'gray')
            ax.axvspan(row['start'], row['end'], color=event_color, alpha=0.3, label=row['type'])

    # Time Format सही करना
    axs[2].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    plt.xticks(rotation=45)

    # Legend (इवेंट्स की पहचान के लिए बॉक्स)
    handles, labels = axs[0].get_legend_handles_labels()
    unique_labels = dict(zip(labels, handles))
    if unique_labels:
        fig.legend(unique_labels.values(), unique_labels.keys(), loc='center right', title="Breathing Events", bbox_to_anchor=(1.12, 0.5))

    # लेआउट को एडजस्ट करें ताकि सब कुछ साफ दिखे
    plt.tight_layout(rect=[0, 0, 0.95, 0.96])
    plt.show()
    print("✅ प्रक्रिया पूरी हुई!")